/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config backend/wrangler.jsonc backend/env.d.ts --include-runtime false` (hash: 3f027fdbb75c676843a41c9fb9bc6446)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./dist/worker");
	}
	interface Env {
		PUBLIC_ORIGIN: "https://cinegen-api.christopherjohnogden.workers.dev";
		MEDIA: R2Bucket;
		DB: D1Database;
		AI: Ai;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PUBLIC_ORIGIN">> {}
}
