// Provider-independent creative directions. Diagrams are drawn by the viewer;
// selecting one never submits a provider job or changes generation settings.
export const FILM_PRESETS = [
  { id: 'establishing-wide', category: 'shot', title: 'Establishing wide', subtitle: 'Let the setting lead', lens: '24 mm', diagram: 'wide', prompt: 'Open on a wide establishing shot, a small subject within a clearly readable environment. Use a 24 mm lens perspective, layered foreground, middle ground and background, and deliberate negative space.' },
  { id: 'intimate-close-up', category: 'shot', title: 'Intimate close-up', subtitle: 'Stay with the emotion', lens: '85 mm', diagram: 'close', prompt: 'Frame an intimate close-up at eye level with an 85 mm lens perspective. Keep the eyes sharp, the background softly separated, and the expression natural. Leave gentle looking room.' },
  { id: 'over-the-shoulder', category: 'shot', title: 'Over the shoulder', subtitle: 'Connect two perspectives', lens: '50 mm', diagram: 'shoulder', prompt: 'Frame an over-the-shoulder dialogue shot with a 50 mm lens perspective. Place the near shoulder softly in the foreground and the speaking subject on the opposite third. Maintain clear eyelines and screen direction.' },
  { id: 'low-angle', category: 'shot', title: 'Low angle', subtitle: 'Give the subject presence', lens: '35 mm', diagram: 'low', prompt: 'Frame the subject from a restrained low camera angle with a 35 mm lens perspective. Use strong vertical lines and a clean silhouette to give the subject presence, without extreme facial distortion.' },
  { id: 'slow-push-in', category: 'camera', title: 'Slow push-in', subtitle: 'Draw attention inward', diagram: 'push', prompt: 'Move the camera forward in a slow, smooth dolly push-in toward the subject. Preserve natural perspective changes, hold focus on the eyes, and keep the movement continuous without a digital zoom or cut.' },
  { id: 'lateral-track', category: 'camera', title: 'Lateral tracking', subtitle: 'Move alongside the action', diagram: 'track', prompt: 'Track the camera laterally alongside the subject at a matching pace. Keep the subject consistently framed while foreground and background show natural parallax. Use a smooth, continuous move.' },
  { id: 'gentle-orbit', category: 'camera', title: 'Gentle orbit', subtitle: 'Reveal a new perspective', diagram: 'orbit', prompt: 'Make a slow, restrained camera orbit around the subject, about a quarter turn. Keep a steady distance and subject scale, with smooth parallax revealing the setting. Avoid a full spin or sudden acceleration.' },
  { id: 'locked-frame', category: 'camera', title: 'Locked frame', subtitle: 'Let the moment unfold', diagram: 'locked', prompt: 'Keep the camera completely locked on a tripod. Use a deliberate static composition and allow the subject and environment to move within it. No pan, tilt, zoom, shake or reframing.' },
  { id: 'soft-window', category: 'lighting', title: 'Soft window light', subtitle: 'Quiet, natural shape', diagram: 'window', prompt: 'Light the subject with a large soft window source from one side. Retain gentle shadow shape on the far cheek with subtle negative fill, natural skin texture and restrained highlights.' },
  { id: 'low-key', category: 'lighting', title: 'Low-key contrast', subtitle: 'Build shape with shadow', diagram: 'lowkey', prompt: 'Use low-key lighting with one controlled side key and deep, readable shadows. Add a restrained edge light for separation, keep the background dark, and protect highlight detail. Avoid flat frontal fill.' },
  { id: 'golden-backlight', category: 'lighting', title: 'Golden backlight', subtitle: 'Warm edges, open shadows', diagram: 'backlight', prompt: 'Place a low warm sun behind the subject to create a delicate rim of light. Balance the face with soft ambient fill, preserve believable skin tones and use restrained flare with detail in the highlights.' },
  { id: 'practical-night', category: 'lighting', title: 'Practical night', subtitle: 'Light from within the scene', diagram: 'practical', prompt: 'Build nighttime lighting around visible practical lamps and motivated light sources. Let warm pools of light fall against a subdued cool ambient background, with rich shadows, natural falloff and controlled reflections.' },
];
